title: Farever Pal
description: A lightweight, out-of-process companion tool for Farever.
theme: jekyll-theme-minimal
show_downloads: true
google_analytics: # Add your ID here if you ever want tracking
